tl_2016_us_cd115.zip:
	curl -OL https://www2.census.gov/geo/tiger/TIGER2016/CD/tl_2016_us_cd115.zip

tl_2016_%_sldu.zip:
	curl -OL https://www2.census.gov/geo/tiger/TIGER2016/SLDU/tl_2016_$*_sldu.zip

tl_2016_%_sldl.zip:
	curl -OL https://www2.census.gov/geo/tiger/TIGER2016/SLDL/tl_2016_$*_sldl.zip
