CA_Congress.csv:
	curl -L http://bdistricting.com/2010/CA_Congress/solution.zip -o CA_Congress-solution.zip
	unzip CA_Congress-solution.zip CA_Congress.csv

CA_Assembly.csv:
	curl -L http://bdistricting.com/2010/CA_Assembly/solution.zip -o CA_Assembly-solution.zip
	unzip CA_Assembly-solution.zip CA_Assembly.csv

CA_Senate.csv:
	curl -L http://bdistricting.com/2010/CA_Senate/solution.zip -o CA_Senate-solution.zip
	unzip CA_Senate-solution.zip CA_Senate.csv

tl_2016_06_tabblock10.shp:
	curl -OL https://www2.census.gov/geo/tiger/TIGER2016/TABBLOCK/tl_2016_06_tabblock10.zip
	unzip tl_2016_06_tabblock10.zip
